services:
  - type: web
    name: sync-video-player
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: ADMIN_PASSWORD
        value: abd123abd
